### ISSUE TITLE
Non transparent background

### ISSUE THREAD

**Issue by Nnadozie** [blueyedgeek/overhaul#32]
Chrome version 62.0.3202.75 (Official Build) (64-bit)
ubuntu 16.04 LTS
![image](https://user-images.githubusercontent.com/15310842/42523822-c52c4530-8466-11e8-823e-9ef25ea52fee.png)

**Comment by Nnadozie** [comment]
Getting rid of these seemed to fix it:
    ``` padding: 6px; ```
    ``` background-color: #fff;```
     ```border-left: 1px solid gray;```
     ```border-right: 1px solid gray;```

![image](https://user-images.githubusercontent.com/15310842/42524173-a38395ae-8467-11e8-8e83-c6b011243b15.png)
```
h1, h2, h3, h4, h5 {
    color: #200;
}
```
![image](https://user-images.githubusercontent.com/15310842/42524222-c7b6edfe-8467-11e8-8916-c5915cd32131.png)
![image](https://user-images.githubusercontent.com/15310842/42524271-eb45c7b8-8467-11e8-8c58-baeff672f1fa.png)

**Comment by Nnadozie** [comment]
I would love to make a PR fixing this issue, and also, nice! It makes nairaland look tons better.

**Comment by thechinedu** [comment]
@Nnadozie the `.container` nested within the `.welcome-message` shouldn't/doesn't have any styling applied to it. I'm not sure why it has style rules applied on your device. Could you clear the browser's cache and reload? Tell me if the errant rules are still showing up after this.

**Comment by Nnadozie** [comment]
Interesting... that worked. The ```.container``` rules are also gone. Instead
```text-align: center;``` and ```color: #fff;``` are apparently inherited from ```.welcome-section```

I also can't replicate the bug after having cleared my cache :(.

**Comment by thechinedu** [comment]
@Nnadozie closing this as the issue has been resolved. 

Thanks.
