### ISSUE TITLE
Posts that have images don't show the images.

### ISSUE THREAD

**Issue by od41** [blueyedgeek/overhaul#36]
Photos were invisible in a post when Overhaul was active. After I disabled it, the images showed up again.

**This is the post**
http://www.nairaland.com/4614474/photos-milliken-hill-road-enugu

**With Overhaul...**
![image](https://user-images.githubusercontent.com/29569725/42679828-82e9bc1a-8683-11e8-9fca-020a1ce7c196.png)

**Without Overhaul...**
![image](https://user-images.githubusercontent.com/29569725/42679850-936fa432-8683-11e8-88f3-bb5301b77d5b.png)

Great work! 👍🏾

**Comment by thechinedu** [comment]
Thanks for bringing this to my attention. A fix has been added and will be part of the next release.
